version: "3"

services:
  k8s-mig-srv-go:
    image: k8s-mig/k8s-mig-srv-go:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GIN_MODE=debug
      - DB_OLD_HOST=k8s-mig-db-old
      - DB_OLD_PORT=5432
      - DB_OLD_NAME=msghub
      - DB_OLD_USER=test001
      - DB_OLD_PASSWORD=test001
      - DB_NEW_HOST=k8s-mig-db-new
      - DB_NEW_PORT=5432
      - DB_NEW_NAME=msghub
      - DB_NEW_USER=test001
      - DB_NEW_PASSWORD=test001
    ports:
      - "9991:3000"

networks:
  default:
    external: true
    name: msghub-backend
